name: SQLProject
description: ''
version: '0.2'
author: null
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/MySQLJob:
    name: MySQLJob
    description: Test
    fabricUID: 10736
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0 45 16 * * ? *
    timeout: null
    alerting:
      emails: pedro.fiadeiro@tpximpact.com
      onStart: true
      onSuccess: true
      onFailure: true
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-04-15 15:26:43'
    author: pedro.fiadeiro@tpximpact.com
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-04-01 09:15:49'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/Department:
    name: Department
    schema:
      providerType: Databricks
      fields:
      - name: DDEPT_KEY
        dataType:
          type: Integer
      - name: ID
        dataType:
          type: String
      - name: AUX_SRC_EFF_FROM_DT
        dataType:
          type: Timestamp
      - name: AUX_SRC_EFF_TO_DT
        dataType:
          type: Timestamp
      - name: AUX_SRC_CUR_FLG
        dataType:
          type: TinyInt
      - name: AUX_SRC_CHANGE_REASON
        dataType:
          type: String
      - name: AUX_SRC_SYS
        dataType:
          type: TinyInt
      - name: AUX_SRC_CRTD_BY
        dataType:
          type: String
      - name: AUX_SRC_CRTD_DTM
        dataType:
          type: Timestamp
      - name: AUX_SRC_UPD_BY
        dataType:
          type: String
      - name: AUX_SRC_UPD_DTM
        dataType:
          type: Timestamp
      - name: AUX_SRC_STATUS
        dataType:
          type: String
      - name: AUX_EFF_FROM_DT
        dataType:
          type: Timestamp
      - name: AUX_EFF_TO_DT
        dataType:
          type: Timestamp
      - name: AUX_CUR_FLG
        dataType:
          type: TinyInt
      - name: AUX_INS_DTM
        dataType:
          type: Timestamp
      - name: AUX_BUS_DT
        dataType:
          type: Timestamp
      - name: DEPT
        dataType:
          type: String
      - name: DEPT_CD
        dataType:
          type: String
      - name: DEPT_NAME
        dataType:
          type: String
    description: null
    author: pedro.fiadeiro@tpximpact.com
    files:
    - models/Department.sql
    - .prophecy/ide/models/Department.json
    sqlDependencies:
      models: []
      datasets: []
    createdAt: '2024-04-01 15:14:18'
sqlMacros: {}
sqlSeeds:
  .prophecy/metadata/sqlseeds/Department_Lookup:
    name: Department_Lookup
    schema:
      providerType: Databricks
      fields:
      - name: DEPARTMENT_ID
        dataType:
          type: Integer
      - name: NAME
        dataType:
          type: String
    description: null
    author: pedro.fiadeiro@tpximpact.com
    files:
    - seeds/Department_Lookup.csv
    createdAt: '2024-04-15 12:15:25'
sqlSources:
  .prophecy/metadata/sqlsources/pedrofiadeiro_hsbc:
    name: pedrofiadeiro.hsbc
    description: null
    author: pedro.fiadeiro@tpximpact.com
    files:
    - prophecy-sources/sources.yml
    createdAt: '2024-04-01 15:25:52'
    tables:
    - name: d_department
      schema:
        providerType: databricks
        fields:
        - name: DDEPT_KEY
          dataType:
            type: Integer
        - name: ID
          dataType:
            type: String
        - name: AUX_SRC_EFF_FROM_DT
          dataType:
            type: Timestamp
        - name: AUX_SRC_EFF_TO_DT
          dataType:
            type: Timestamp
        - name: AUX_SRC_CUR_FLG
          dataType:
            type: TinyInt
        - name: AUX_SRC_CHANGE_REASON
          dataType:
            type: String
        - name: AUX_SRC_SYS
          dataType:
            type: TinyInt
        - name: AUX_SRC_CRTD_BY
          dataType:
            type: String
        - name: AUX_SRC_CRTD_DTM
          dataType:
            type: Timestamp
        - name: AUX_SRC_UPD_BY
          dataType:
            type: String
        - name: AUX_SRC_UPD_DTM
          dataType:
            type: Timestamp
        - name: AUX_SRC_STATUS
          dataType:
            type: String
        - name: AUX_EFF_FROM_DT
          dataType:
            type: Timestamp
        - name: AUX_EFF_TO_DT
          dataType:
            type: Timestamp
        - name: AUX_CUR_FLG
          dataType:
            type: TinyInt
        - name: AUX_INS_DTM
          dataType:
            type: Timestamp
        - name: AUX_BUS_DT
          dataType:
            type: Timestamp
        - name: DEPT
          dataType:
            type: String
        - name: DEPT_CD
          dataType:
            type: String
        - name: DEPT_NAME
          dataType:
            type: String
      description: null
      author: pedro.fiadeiro@tpximpact.com
      createdAt: '2024-04-01 15:25:52'
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: pedro.fiadeiro@tpximpact.com
  createdAt: '2024-04-01 09:15:49'
dependencies: '[]'
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
